USE [PruebaEcop]
GO

/****** Object:  Table [dbo].[PEDIDO_CABECERA]    Script Date: 22/5/2024 07:37:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PEDIDO_CABECERA](
	[PEDIDO_ID] [int] IDENTITY(1,1) NOT NULL,
	[CLIENTE_ID] [int] NULL,
	[DESCRIPCION] [varchar](200) NULL,
	[CANTIDAD_TOTAL] [float] NULL,
	[PRECIO_TOTAL] [decimal](18, 0) NULL,
	[ESTADO] [varchar](50) NULL,
	[FECHA_INGRESO] [date] NULL,
	[FECHA_ENTREGA] [date] NULL,
 CONSTRAINT [PK_PEDIDO_CABECERA] PRIMARY KEY CLUSTERED 
(
	[PEDIDO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


